FROM python:3.9

WORKDIR /app

COPY backend/requirements.txt ./
RUN pip install -r requirements.txt

COPY backend/api.py ./
COPY backend/connection_db /app/connection_db

EXPOSE 5000

CMD ["python", "api.py"]